// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.15.6
// source: encoder/encoder.proto

package encoder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EncodeBlobRequest contains data and pre-computed encoding params provided to Encoder
type EncodeBlobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data        []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	RequireData bool   `protobuf:"varint,2,opt,name=require_data,json=requireData,proto3" json:"require_data,omitempty"`
}

func (x *EncodeBlobRequest) Reset() {
	*x = EncodeBlobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoder_encoder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodeBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeBlobRequest) ProtoMessage() {}

func (x *EncodeBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encoder_encoder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeBlobRequest.ProtoReflect.Descriptor instead.
func (*EncodeBlobRequest) Descriptor() ([]byte, []int) {
	return file_encoder_encoder_proto_rawDescGZIP(), []int{0}
}

func (x *EncodeBlobRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncodeBlobRequest) GetRequireData() bool {
	if x != nil {
		return x.RequireData
	}
	return false
}

// EncodeBlobReply
type EncodeBlobReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version           uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ErasureCommitment []byte   `protobuf:"bytes,2,opt,name=erasure_commitment,json=erasureCommitment,proto3" json:"erasure_commitment,omitempty"`
	StorageRoot       []byte   `protobuf:"bytes,3,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	EncodedData       []byte   `protobuf:"bytes,4,opt,name=encoded_data,json=encodedData,proto3" json:"encoded_data,omitempty"`
	EncodedSlice      [][]byte `protobuf:"bytes,5,rep,name=encoded_slice,json=encodedSlice,proto3" json:"encoded_slice,omitempty"`
}

func (x *EncodeBlobReply) Reset() {
	*x = EncodeBlobReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoder_encoder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodeBlobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeBlobReply) ProtoMessage() {}

func (x *EncodeBlobReply) ProtoReflect() protoreflect.Message {
	mi := &file_encoder_encoder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeBlobReply.ProtoReflect.Descriptor instead.
func (*EncodeBlobReply) Descriptor() ([]byte, []int) {
	return file_encoder_encoder_proto_rawDescGZIP(), []int{1}
}

func (x *EncodeBlobReply) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncodeBlobReply) GetErasureCommitment() []byte {
	if x != nil {
		return x.ErasureCommitment
	}
	return nil
}

func (x *EncodeBlobReply) GetStorageRoot() []byte {
	if x != nil {
		return x.StorageRoot
	}
	return nil
}

func (x *EncodeBlobReply) GetEncodedData() []byte {
	if x != nil {
		return x.EncodedData
	}
	return nil
}

func (x *EncodeBlobReply) GetEncodedSlice() [][]byte {
	if x != nil {
		return x.EncodedSlice
	}
	return nil
}

var File_encoder_encoder_proto protoreflect.FileDescriptor

var file_encoder_encoder_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72,
	0x22, 0x4a, 0x0a, 0x11, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0xc5, 0x01, 0x0a,
	0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x12, 0x65, 0x72,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x65, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53,
	0x6c, 0x69, 0x63, 0x65, 0x32, 0x4f, 0x0a, 0x07, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x12,
	0x44, 0x0a, 0x0a, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x1a, 0x2e,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x6c,
	0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x67, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x30, 0x67, 0x2d, 0x64, 0x61,
	0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encoder_encoder_proto_rawDescOnce sync.Once
	file_encoder_encoder_proto_rawDescData = file_encoder_encoder_proto_rawDesc
)

func file_encoder_encoder_proto_rawDescGZIP() []byte {
	file_encoder_encoder_proto_rawDescOnce.Do(func() {
		file_encoder_encoder_proto_rawDescData = protoimpl.X.CompressGZIP(file_encoder_encoder_proto_rawDescData)
	})
	return file_encoder_encoder_proto_rawDescData
}

var file_encoder_encoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_encoder_encoder_proto_goTypes = []interface{}{
	(*EncodeBlobRequest)(nil), // 0: encoder.EncodeBlobRequest
	(*EncodeBlobReply)(nil),   // 1: encoder.EncodeBlobReply
}
var file_encoder_encoder_proto_depIdxs = []int32{
	0, // 0: encoder.Encoder.EncodeBlob:input_type -> encoder.EncodeBlobRequest
	1, // 1: encoder.Encoder.EncodeBlob:output_type -> encoder.EncodeBlobReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_encoder_encoder_proto_init() }
func file_encoder_encoder_proto_init() {
	if File_encoder_encoder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encoder_encoder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodeBlobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encoder_encoder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodeBlobReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encoder_encoder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encoder_encoder_proto_goTypes,
		DependencyIndexes: file_encoder_encoder_proto_depIdxs,
		MessageInfos:      file_encoder_encoder_proto_msgTypes,
	}.Build()
	File_encoder_encoder_proto = out.File
	file_encoder_encoder_proto_rawDesc = nil
	file_encoder_encoder_proto_goTypes = nil
	file_encoder_encoder_proto_depIdxs = nil
}
