version: '3'
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    ports:
      - 8545:8545
    networks:
      - zgda-demo
    command: ["anvil --host 0.0.0.0"]
networks:
  zgda-demo:
    name: zgda-demo
